version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env.prod
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
